# Site settings
title: Naoki Kano project page
email: naokikano@dewildequinten.be
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "dewildequinten.be/works/auotmationcollective" # the base hostname & protocol for your site
#github_username:  naokikano
#instagram_username: _naokikano_

# Build settings
markdown: kramdown
permalink: pretty
